- name: to find uname -a output
  hosts: frontend
  become: yes
  tasks:
  - name: find uname -a output
    ansible.builtin.command:
      cmd: uname -a
    register: uname-a_output
  - name: show the uname -a output
    ansible.builtin.debug:
      var: uname-a_output
    
