- name: install nginx package
  hosts: local
  connection: local
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "RedHat"
 
  - name: install nginx if debian
    ansbile.builtin.apt:
      name: nginx
      state: lates
    when: ansible_os_family == "Debian"