- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps,Shell,Ansible
    tags:
      Application: payment
      Environment: dev
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "{{ name | default('Balu') }}"
  - name: string in to list
    ansible.builtin.debug:
      msg: "{{ technologies | split(',') }}"
  - name: dictonary to map
    ansible.builtin.debug:
      msg: "{{ tags|dict2items   }}"