- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check id roboshop is exist or not
    ansible.builtin.command:
      cmd: id roboshop
    register: user_output
    ignore_errors: true
  - name: print the user output
    ansible.builtin.debug:
      msg: "{{ user_output }}"
  - name: creating roboshop id
    ansible.builtin.command:
      cmd: useradd roboshop
    when: user_output!= 0